### ISSUE TITLE
Lo hago para cumplir la tarea

### ISSUE THREAD

**Issue by TomGarb** [pdepjm/2023-tp0-presentacion-MorosiniP#1]
Buena presentación, podrías agregarle alguna serie o película que te guste así sabemos mas de vos

**Comment by MorosiniP** [comment]
Buenas!! Gracias por el feedback
Sii, es verdad lo podria agregar! No lo pense poner porque no tengo un gusto espcifico te miro todo je
Saludos

**Comment by TomGarb** [comment]
Esta perfecto que mires de todo, a mi me pasa con la musica, no llego a tener una banda o un estilo de musica que prefiera mas que otro.
