### ISSUE TITLE
Jugador favorito river

### ISSUE THREAD

**Issue by gbergera** [pdepjm/2023-tp0-presentacion-MorosiniP#2]
Cual jugador del plantel preferis?

**Comment by MorosiniP** [comment]
Del plantel actual  banco a morir al colibri Borja nos va a dar muchas alegrias
Y uno que es que admiro y me volvia loco verlo jugar es Jusanfer

Vos cual es el tuyo?

**Comment by gbergera** [comment]
yo banco a morir a Enzo Perez y estoy esperando a nico de la Cruz para que vuelva ese mediocampo del 2019(ojala porque depende de micho)

**Comment by MorosiniP** [comment]
Sii ojala, y traer un central urgente, después del partido de Diaz hoy...
Mejor cierro el issue porque si no me banean si opino del partido (?
